#!/usr/bin/env python3
"""Regenerate packages/shared/src/studio/tables.ts from the UI/UX Pro Max data.

    git clone --depth 1 https://github.com/nextlevelbuilder/ui-ux-pro-max-skill /tmp/uipro
    python3 tools/studio-tables.py /tmp/uipro/src/ui-ux-pro-max/data

The data is MIT (Next Level Builder); docs/third-party.md records the terms.
Three files are read: products.csv (192 product types with keywords, styles and
page patterns), colors.csv (a semantic palette per product type) and
typography.csv (74 font pairings). Nothing is edited by hand in the output.
"""
import csv
import json
import os
import sys

data = sys.argv[1] if len(sys.argv) > 1 else "/tmp/uipro/src/ui-ux-pro-max/data"
out = os.path.join(os.path.dirname(__file__), "..", "packages", "shared", "src", "studio", "tables.ts")


def words(s):
    return [w.strip().lower() for w in s.split(",") if w.strip()]


products = list(csv.DictReader(open(os.path.join(data, "products.csv"), encoding="utf-8")))
colors = {r["Product Type"]: r for r in csv.DictReader(open(os.path.join(data, "colors.csv"), encoding="utf-8"))}
fonts = list(csv.DictReader(open(os.path.join(data, "typography.csv"), encoding="utf-8")))

rows = []
for r in products:
    c = colors.get(r["Product Type"])
    if not c:
        print("no palette for", r["Product Type"], file=sys.stderr)
        continue
    styles = [x.strip() for x in (r["Primary Style Recommendation"] + " + " + r["Secondary Styles"]).replace(" , ", " + ").split("+") if x.strip()]
    rows.append(
        {
            "t": r["Product Type"],
            "k": words(r["Keywords"]),
            "s": styles,
            "l": r["Landing Page Pattern"],
            "d": r["Dashboard Style (if applicable)"],
            "f": r["Color Palette Focus"],
            "c": {"p": c["Primary"], "op": c["On Primary"], "s": c["Secondary"], "a": c["Accent"], "oa": c["On Accent"], "bg": c["Background"], "fg": c["Foreground"], "card": c["Card"], "cf": c["Card Foreground"], "m": c["Muted"], "mf": c["Muted Foreground"], "b": c["Border"], "x": c["Destructive"]},
        }
    )
pairings = [{"n": r["Font Pairing Name"], "h": r["Heading Font"], "b": r["Body Font"], "cat": r["Category"], "k": words(r["Mood/Style Keywords"]), "f": words(r["Best For"])} for r in fonts]

HEADER = '''/**
 * The studio's tables: what kinds of product exist, which palette, style
 * and page pattern each has earned, and which type pairings suit which
 * moods. Generated by tools/studio-tables.py from the data files of
 * nextlevelbuilder/ui-ux-pro-max-skill (MIT, Next Level Builder); the
 * terms and the provenance are in docs/third-party.md. Do not edit by
 * hand; edit the script.
 */
export interface Palette {
  /** primary, on-primary, secondary, accent, on-accent, background, foreground, card, card-foreground, muted, muted-foreground, border, destructive */
  p: string; op: string; s: string; a: string; oa: string; bg: string; fg: string; card: string; cf: string; m: string; mf: string; b: string; x: string;
}
export interface ProductRow {
  /** The product type's name. */
  t: string;
  /** Words that point to it. */
  k: string[];
  /** Styles that suit it, best first. */
  s: string[];
  /** The landing page pattern and the main screen's kind. */
  l: string;
  d: string;
  /** What the palette is for, in a phrase. */
  f: string;
  c: Palette;
}
export interface FontRow {
  n: string;
  /** Heading and body families (Google Fonts), and the pairing's categories, e.g. "Serif + Sans". */
  h: string;
  b: string;
  cat: string;
  /** Mood words and what it is best for. */
  k: string[];
  f: string[];
}
'''
with open(out, "w", encoding="utf-8") as f:
    f.write(HEADER)
    f.write("export const PRODUCTS: ProductRow[] = " + json.dumps(rows, ensure_ascii=False, separators=(",", ":")) + ";\n")
    f.write("export const FONTS: FontRow[] = " + json.dumps(pairings, ensure_ascii=False, separators=(",", ":")) + ";\n")
print(len(rows), "products,", len(pairings), "pairings →", os.path.relpath(out))
